# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cb063125384601432f6c16882c7d99d4e552d80ed9610d1c3fd3c6eaa3182b0e7cdb1463cfe7e3ac12ccd22f3ef57ee445328d040ca1edd2fefe5bf6705a6e3

test:
  secret_key_base: ee8629a593ce6d35c1611b68701f9e7b1a62df3f31f01201814a845b3c6a2292dfb5b26191f4835bcf71363bffa8dd43652ce186bd54e267137c25e45beab497

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
